version: "3"

services:
  persistent-db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quicktrade_dev
    ports:
      - "5432:5432"
    volumes:
      - ./server/db/data:/var/lib/postgresql/data
